item {
  id: 1
  name: 'limbo'
}

item {
  id: 2
  name: 'limbo_white'
}

item {
  id: 3
  name: 'box'
}

item {
  id: 4
  name: 'ship'
}

item {
  id: 5
  name: 'spider'
}

item {
  id: 6
  name: 'rock'
}

item {
  id: 7
  name: 'rope'
}

item {
  id: 8
  name: 'trap'
}

item {
  id: 9
  name: 'gear'
}

item {
  id: 10
  name: 'lever'
}

item {
  id: 11
  name: 'ladder'
}

item {
  id: 12
  name: 'gun'
}

item {
  id: 13
  name: 'button'
}

item {
  id: 14
  name: 'fly'
}